<?php

namespace Organizer\OrganizerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetsRepository extends EntityRepository
{
}
