<?php

namespace Organizer\OrganizerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SousTachesTimelineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousTachesTimelineRepository extends EntityRepository
{
}
