<?php

namespace Organizer\OrganizerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserXProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserXProjetRepository extends EntityRepository
{
}
